In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/data.csv")

In [2]:
df.head()

,game_id,subframe,won,playfield,x,y,r,placed,hold,next,...,garbage_cleared,attack,t_spin,btb,combo,immediate_garbage,incoming_garbage,rating,glicko,glicko_rd
0,1,67,1,NaN,4,0,N,I,N,JZSOTLSLIOJZTJ,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
1,1,170,1,NNNIIII,4,1,N,Z,J,SOTLSLIOJZTJTZ,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
2,1,339,1,NNNIIIINNNNNNNZZNNNNNNNZZ,6,1,E,S,J,OTLSLIOJZTJTZS,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
3,1,472,1,NNNIIIISNNNNNNZZSSNNNNNZZNS,8,0,N,O,J,TLSLIOJZTJTZSO,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
4,1,602,1,NNNIIIISOONNNNZZSSOONNNZZNS,0,1,E,J,T,LSLIOJZTJTZSOI,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624

### Removing Unnecessary Variables

In [2]:

unneeded_cols = ["playfield", "x", "y", "r", "next", "hold", "placed"]
present_unneeded = [col for col in unneeded_cols if col in df.columns]
df = df.drop(columns=present_unneeded)

In [4]:
df.head()

,game_id,subframe,won,cleared,garbage_cleared,attack,t_spin,btb,combo,immediate_garbage,incoming_garbage,rating,glicko,glicko_rd
0,1,67,1,0,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
1,1,170,1,0,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
2,1,339,1,0,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
3,1,472,1,0,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
4,1,602,1,0,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624

### Checking for Multiple Representations

In [3]:
df['won'].value_counts()

won
1    4274700
0    3441824
Name: count, dtype: int64

In [6]:
df['t_spin'].value_counts()

t_spin
N    7150022
F     527604
M      38898
Name: count, dtype: int64

### Checking For Missing Data

In [14]:
df.isnull().any()

game_id              False
subframe             False
won                  False
cleared              False
garbage_cleared      False
attack               False
t_spin               False
btb                  False
combo                False
immediate_garbage    False
incoming_garbage     False
rating               False
glicko               False
glicko_rd            False
dtype: bool

### Checking for Negative Values

In [21]:
numeric_cols = df.select_dtypes(include=['number'])
negative_counts = (numeric_cols < 0).sum()
print(negative_counts)

game_id              0
subframe             0
won                  0
cleared              0
garbage_cleared      0
attack               0
btb                  0
combo                0
immediate_garbage    0
incoming_garbage     0
rating               0
glicko               0
glicko_rd            0
dtype: int64

### Checking for Incorrect Datatypes

In [4]:
df.dtypes

game_id                int64
subframe               int64
won                    int64
cleared                int64
garbage_cleared        int64
attack                 int64
t_spin                object
btb                    int64
combo                  int64
immediate_garbage      int64
incoming_garbage       int64
rating               float64
glicko               float64
glicko_rd            float64
dtype: object

In [ ]:
# Convert integer columns to smallest possible integer type,
# and float columns to smallest possible float type.
int_cols = [
    "won",
    "game_id",
    "subframe",
    "cleared",
    "garbage_cleared",
    "attack",
    "btb",
    "combo",
    "immediate_garbage",
    "incoming_garbage",
]
float_cols = ["rating", "glicko", "glicko_rd"]
for col in int_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], downcast="integer", errors="coerce")
for col in float_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], downcast="float", errors="coerce")

# state that this is for optimization purposes

In [ ]:
df.dtypes

### Checking for Default Values and Inconsistent Formatting

In [5]:
for col in df:
  print(f"{col}: {df[col].unique()}")
  print("")

game_id: [     1      2      3 ... 124030 124031 124032]

subframe: [    67    170    339 ... 102556 103224 103661]

won: [1 0]

cleared: [0 2 1 4 3]

garbage_cleared: [0]

attack: [ 0  4  1  5  3  6  2  7  8 10  9 11 12 14 15 16 17 13 19 18 22 20]

t_spin: ['N' 'F' 'M']

btb: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54]

combo: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

immediate_garbage: [ 0  7  8  4  2  1  6 10 13  5  3  9 11 15 12 14 20 16 19 23 22 18 28 17
 21 26 25 24 31 27 32 36 30 40 35 41 33 29 34 38 37 69 78 49 42 50 43 51
 39 46 59 58 77 61 52 56]

incoming_garbage: [ 0  7 15  9  2  1  4  6  5  3 13 10 11  8 16 12 14 18 20 19 23 29 17 28
 22 24 21 26 25 27 31 32 34 36 30 40 35 41 33 38 37 69 78 49 42 50 43 51
 39 46 66 58 77 74 52 56 59 44]

rating: [24748.52148438 24820.7109375  24788.74414062 24830.14648438
 24859.94726562 24887.21679688 24864.00195312 24961.0234375
 24713.24414062 24827.4140625  24737.203125   24999.52148438
 24991.89257812 24730.4140625  24886.38671875 24929.58984375
 24832.296875   24709.61328125 24917.9140625  24825.25
 24808.39453125 24910.67578125 24713.30664062 24904.13867188
 24964.734375   24952.47265625 24952.4921875  24967.29101562
 24872.34570312 24876.94726562 24857.99023438 24924.22851562
 24834.79101562 24930.44726562 24967.19335938 24974.69140625
 24984.18554688 24767.9375     24914.42578125 24916.20703125
 24886.3359375  24825.11914062 24805.04492188 24750.25
 24755.09960938 24797.26171875 24828.45703125 24894.140625
 24937.1953125  24894.42382812 24917.06445312 24726.19140625
 24766.16210938 24778.4921875  24724.65820312 24867.15234375
 24915.484375   24967.26367188 24987.77734375 24909.37109375
 24933.68359375 24968.21289062 24968.54882812 24882.125
 24847.6328125  24970.16601562 24855.3671875  24820.375
 24704.046875   24936.00390625 24705.21484375 24875.890625
 24995.03515625 24946.27148438 24804.07617188 24763.99804688
 24846.75585938 24777.9609375  24921.703125   24907.27539062
 24906.328125   24829.33984375 24704.90429688 24967.69335938
 24993.1875     24966.7109375  24918.98632812 24984.78125
 24832.32617188 24966.24023438 24952.32421875 24986.44335938
 24774.99414062 24804.71484375 24917.5234375  24903.61523438
 24922.3828125  24850.23242188 24886.25390625 24966.74414062
 24866.59765625 24960.0546875  24722.1796875  24766.71679688
 24902.82226562 24974.93359375 24819.6015625  24941.43359375
 24992.703125   24993.37109375 24963.10546875 24834.36328125
 24741.56835938 24958.17578125 24992.84960938 24948.86132812
 24826.20898438 24798.6953125  24986.93359375 24854.15429688
 24713.00976562 24766.1640625  24978.75976562 24889.35546875
 24933.69335938 24887.78515625 24901.         24892.734375
 24806.29882812 24870.9140625  24984.25       24884.78515625
 24842.48242188 24886.2578125  24739.92578125 24769.52734375
 24998.671875   24997.00195312 24998.93359375 24798.24609375
 24736.40039062 24895.00390625 24954.29296875 24854.8125
 24991.68945312 24958.796875   24900.8828125  24763.46289062
 24973.40820312 24953.33398438 24964.16601562 24987.08984375
 24993.91015625 24989.59375    24705.62109375 24766.66210938
 24767.8671875  24734.80664062 24720.91992188 24908.54882812
 24983.65820312 24730.06054688 24728.65234375 24719.24804688
 24780.74609375 24913.30664062 24910.86132812 24880.11328125
 24963.17382812 24790.30273438 24771.69726562 24699.23242188
 24712.28710938 24939.51367188 24771.61132812 24953.59960938
 24712.21679688 24796.93359375 24967.18554688 24976.8203125
 24801.23632812 24785.734375   24802.02539062 24758.44726562
 24755.80273438 24924.50976562 24753.51367188 24866.14648438
 24898.13085938 24978.76171875 24726.50585938 24705.68359375
 24783.46484375 24736.99023438 24874.74414062 24743.046875
 24908.62304688 24905.26367188 24891.92578125 24708.29296875
 24931.3203125  24715.37890625 24958.45703125 24780.59570312
 24840.68945312 24814.93164062 24964.86132812 24776.51367188
 24936.50585938 24710.98046875 24954.5546875  24885.74804688
 24816.09179688 24953.42578125 24965.05859375 24948.42382812
 24884.2265625  24978.0859375  24724.73828125 24927.80273438
 24965.65039062 24932.29882812 24987.38867188 24982.56640625
 24984.3828125  24798.13085938 24732.0859375  24836.44140625
 24871.70117188 24882.68164062 24873.54882812 24802.390625
 24998.86132812 24998.97265625 24930.5234375  24827.609375
 24786.44335938 24757.734375   24922.74023438 24918.765625
 24913.34765625 24757.06640625 24919.62695312 24923.7734375
 24925.14648438 24711.02539062 24930.203125   24958.91210938
 24728.03515625 24978.92382812 24708.140625   24753.25
 24868.56054688 24951.5859375  24710.39257812 24975.09765625
 24832.38867188 24913.23632812 24915.17773438 24980.4609375
 24995.24414062 24780.73242188 24700.4609375  24930.953125
 24773.16015625 24740.015625   24711.76757812 24802.37890625
 24749.61328125 24948.81835938 24770.15820312 24798.98242188
 24849.01757812 24988.41992188 24764.48242188 24987.23046875
 24858.04101562 24833.46289062 24986.65820312 24941.640625
 24997.12890625 24995.21289062 24767.8203125  24888.34765625
 24890.31445312 24826.51367188 24759.1171875  24904.76367188
 24907.875      24999.2265625  24958.99804688 24801.98632812
 24829.80078125 24971.40429688 24743.98242188 24821.46875
 24845.71289062 24971.57617188 24938.109375   24904.59375
 24974.47070312 24805.10546875 24740.14257812 24981.703125
 24829.84765625 24868.43359375 24714.20898438 24745.89648438
 24979.98632812 24879.50195312 24726.58203125 24854.11132812
 24718.81054688 24950.1328125  24742.10546875 24775.98828125
 24758.03320312 24911.1640625  24736.77929688 24846.92382812
 24927.6796875  24940.97070312 24817.90429688 24914.20703125
 24860.79296875 24996.79882812 24881.52148438 24848.15820312
 24925.10546875 24750.02539062 24941.3203125  24892.97070312
 24714.67578125 24711.70703125 24855.11132812 24855.29492188
 24754.22265625 24980.10742188 24908.78125    24854.3828125
 24839.40234375 24910.90625    24774.08789062 24707.42578125
 24739.2890625  24703.3671875  24844.0859375  24893.0546875
 24899.9609375  24702.86328125 24744.36914062 24904.50390625
 24849.51367188 24940.67578125 24861.546875   24790.9453125
 24951.27539062 24980.47070312 24864.13085938 24954.94921875
 24716.33789062 24718.02539062 24834.28125    24985.39257812
 24950.38867188 24805.1796875  24854.05859375 24833.52148438
 24792.19726562 24875.2265625  24698.32421875 24984.56054688
 24777.52539062 24880.12890625 24964.18359375 24988.359375
 24989.22460938 24777.22265625 24732.35742188 24859.4375
 24705.18554688 24724.53320312 24983.17773438 24930.8671875
 24927.77539062 24705.67382812 24945.84570312 24979.5546875
 24875.46289062 24818.54882812 24986.8671875  24746.52148438
 24957.203125   24925.12304688 24972.20703125 24874.13085938
 24989.39648438 24945.80273438 24832.98046875 24843.67382812
 24982.59375    24964.94335938 24854.55273438 24905.8671875
 24967.43554688 24863.0546875  24949.1640625  24910.97265625
 24708.03710938 24747.53710938 24993.93554688 24942.76171875
 24701.66210938 24857.76953125 24719.10351562 24974.3046875
 24734.41796875 24954.66601562 24768.375      24995.00976562
 24794.84960938 24717.0859375  24844.48632812 24983.48242188
 24901.81640625 24870.39648438 24939.99414062 24729.76757812
 24712.546875   24755.90039062 24863.47070312 24743.76367188
 24707.27929688 24808.79492188 24958.87109375 24996.57617188
 24736.48242188 24740.04101562 24748.25390625 24859.75195312
 24978.44140625 24708.35351562 24724.66992188 24781.5625
 24959.70898438 24916.77148438 24765.00390625 24772.58203125
 24738.13085938 24734.87304688 24798.4765625  24742.29296875
 24742.71679688 24982.875      24921.29492188 24907.65234375
 24991.51757812 24990.72070312 24704.42382812 24775.7109375
 24806.0546875  24771.93554688 24704.58007812 24699.66015625
 24729.9921875  24813.96679688 24700.94335938 24716.84179688
 24826.921875   24781.72460938 24866.28125    24699.09375
 24792.16992188 24725.73828125 24760.60546875 24841.3671875
 24923.4140625  24971.82617188 24707.05078125 24698.078125
 24872.7421875  24738.56445312 24777.04296875 24707.30859375
 24762.96679688 24956.55859375 24953.96875   ]

glicko: [2701.88769531 2791.86694336 2748.19384766 2810.68676758 2856.23876953
 2921.94799805 2867.17602539 3193.43676758 2668.73828125 2811.63354492
 2694.09741211 4373.41992188 3606.390625   2683.19628906 2917.22607422
 3043.38476562 2809.01074219 2677.77612305 2998.0534668  2806.0456543
 2780.39038086 2976.21459961 2666.36816406 2965.27880859 3219.05810547
 3161.76049805 3148.01806641 3241.78442383 2883.42236328 2894.95654297
 2852.46777344 3018.0234375  2813.2590332  3041.14868164 3238.32104492
 3327.24121094 3430.53808594 2723.65039062 2986.76074219 2998.9921875
 2912.19921875 2797.8996582  2768.95214844 2703.54345703 2710.07519531
 2758.68212891 2808.7890625  2930.23535156 3067.26147461 2934.39111328
 2994.5859375  2688.29321289 2721.55786133 2735.40722656 2678.08398438
 2870.94189453 2989.67138672 3241.66333008 3497.8293457  2971.41552734
 3053.20141602 3246.93554688 3251.95581055 2902.40063477 2842.30395508
 3263.3137207  2848.35644531 2790.6652832  2662.07958984 3062.37573242
 2665.88891602 2888.30761719 3738.3203125  3110.00268555 2768.16992188
 2718.68383789 2832.23388672 2734.83154297 3009.77294922 2974.01782227
 2968.29614258 2804.609375   2663.22045898 3246.90600586 3653.15917969
 3234.61132812 3005.19189453 3440.99487305 2808.75       3230.70361328
 3143.55224609 3470.34326172 2732.71118164 2768.78588867 2996.35327148
 2954.78857422 3012.32006836 2843.30688477 2911.52124023 3234.81176758
 2869.4387207  3194.42358398 2675.34472656 2721.71313477 2952.99633789
 3310.58935547 2789.96337891 3103.16601562 3633.47241211 3665.80639648
 3208.55981445 2818.6730957  2694.66918945 3181.07470703 3641.37182617
 3121.75805664 2799.96826172 2760.36303711 3479.99365234 2845.79711914
 2666.72338867 2721.01245117 3358.37133789 2918.50219727 3053.3527832
 2914.9387207  2948.24047852 2927.23120117 2771.97973633 2878.04003906
 3435.59936523 2907.97802734 2825.58203125 2911.36303711 2692.81958008
 2724.83447266 4080.13330078 3866.01464844 4139.84667969 2761.74609375
 2692.54248047 2932.78442383 3151.78369141 2846.91772461 3599.60424805
 3190.13623047 2947.21704102 2718.04711914 3293.86987305 3152.53076172
 3215.89453125 3484.44604492 3682.38134766 3540.67749023 2660.79345703
 2721.86572266 2733.66040039 2689.69726562 2674.63598633 2970.68823242
 3421.56518555 2687.77587891 2682.5144043  2688.27978516 2738.50634766
 2988.13696289 2976.30273438 2898.24072266 3218.47607422 2749.80249023
 2727.51464844 2654.65527344 2670.09716797 3077.78588867 2727.64404297
 3147.04638672 2667.01708984 2762.22216797 3238.48291016 3336.4050293
 2764.29833984 2744.30957031 2768.76025391 2712.2109375  2711.06542969
 3019.34130859 2707.90722656 2871.44921875 2940.3425293  3353.62451172
 2679.87963867 2659.91699219 2741.35424805 2690.08129883 2886.98510742
 2696.265625   2974.02685547 2961.95361328 2926.17626953 2662.55639648
 3045.83422852 2668.79003906 3177.8659668  2750.00878906 2825.03686523
 2782.96313477 3220.2800293  2733.23046875 3064.91430664 2664.8894043
 3159.43774414 2910.54833984 2789.10375977 3150.30419922 3221.75146484
 3119.85375977 2910.82055664 3344.87036133 2679.36401367 3044.91064453
 3226.8034668  3048.01025391 3489.27441406 3418.41235352 3434.65063477
 2760.93237305 2685.16064453 2816.04931641 2881.8684082  2914.11645508
 2883.63867188 2765.8840332  4127.34423828 4153.10693359 3041.33447266
 2804.42138672 2744.9753418  2713.69580078 3013.00805664 3000.68969727
 2983.31298828 2713.18969727 3004.25048828 3016.71557617 3021.61010742
 2666.59887695 3049.21826172 3179.57421875 2683.40332031 3354.43530273
 2662.68798828 2706.94506836 2874.89453125 3135.90991211 2664.36743164
 3312.60913086 2808.73925781 2982.76708984 2989.40454102 3375.35961914
 3744.54174805 2739.01538086 2655.12939453 3042.65844727 2730.67163086
 2693.32275391 2665.84570312 2766.92895508 2702.80664062 3122.10058594
 2727.37011719 2761.24023438 2847.98950195 3513.93994141 2720.78833008
 3487.24121094 2852.96630859 2814.40185547 3475.82641602 3087.01855469
 3878.85327148 3759.64501953 2723.03930664 2918.92602539 2921.09350586
 2800.17675781 2713.35131836 2958.41455078 2969.70361328 4221.25341797
 3180.48144531 2764.66357422 2808.59545898 3274.71289062 2697.38989258
 2792.05224609 2838.61401367 3276.82543945 3075.71069336 2961.78100586
 3303.7746582  2769.05566406 2695.6081543  3392.04443359 2807.28881836
 2872.890625   2673.09082031 2699.015625   3368.64257812 2896.59594727
 2681.77490234 2845.99414062 2672.66674805 3130.74584961 2695.06396484
 2732.73999023 2711.84643555 2977.07055664 2691.20898438 2833.0847168
 3030.29492188 3084.67407227 2786.76928711 2985.69335938 2858.08251953
 3854.64160156 2900.3293457  2835.72119141 3021.25610352 2703.57519531
 3084.85986328 2928.85302734 2668.99633789 2665.92993164 2848.04467773
 2848.34912109 2708.22070312 3370.19970703 2970.03491211 2847.46435547
 2822.12915039 2975.66943359 2731.46411133 2661.50708008 2692.4230957
 2660.03417969 2830.3112793  2927.84472656 2945.64990234 2657.51660156
 2697.07250977 2964.04638672 2837.03076172 3082.61206055 2860.46435547
 2750.81469727 3135.08862305 3374.90185547 2867.32080078 3158.11669922
 2669.72314453 2674.52368164 2813.18212891 3452.45019531 3130.3046875
 2769.32714844 2846.77856445 2811.07006836 2752.58349609 2888.3737793
 2653.46704102 3436.04541016 2735.32763672 2897.5690918  3219.52319336
 3512.69287109 3532.08349609 2735.33984375 2685.93505859 2856.00195312
 2662.64013672 2677.99169922 3414.39111328 3043.24829102 3032.08984375
 2659.83300781 3107.69702148 3362.94384766 2887.44091797 2788.25219727
 3482.62866211 3374.9050293  2700.32666016 3171.29052734 3021.21118164
 3282.71655273 2885.02001953 3536.13012695 3106.73291016 2810.87280273
 2827.66186523 3418.30053711 3221.27954102 2846.59594727 2974.01513672
 3240.92724609 2862.30102539 3123.38305664 2986.74975586 2662.15161133
 2701.05102539 3683.42358398 3092.60644531 2656.66113281 2856.84326172
 2672.93310547 3303.34155273 2687.42602539 3154.06787109 2723.31176758
 3732.38696289 2758.91040039 2675.57543945 2828.78564453 3419.62719727
 2951.38476562 2877.08862305 3079.59472656 2685.5871582  2666.34594727
 2710.19140625 2865.8046875  2698.32495117 2661.56323242 2778.97070312
 3180.10913086 3837.4152832  2689.13891602 2695.11181641 2701.48901367
 2856.24902344 3371.85668945 2662.47998047 2677.98388672 2739.69433594
 3184.68359375 2993.3671875  2719.91967773 2729.82910156 2692.23779297
 2687.87475586 2760.51269531 2702.22753906 2695.87646484 3430.98608398
 3009.29980469 2966.5925293  3595.38061523 3573.91650391 2658.88793945
 2732.09326172 2770.46435547 2727.68188477 2662.19360352 2654.79711914
 2682.47583008 2787.11767578 2660.31835938 2670.19482422 2813.19018555
 2739.17529297 2869.59936523 2656.92504883 2756.57250977 2679.00927734
 2725.82788086 2825.39770508 3020.92553711 3278.64306641 2661.06811523
 2661.69384766 2881.78369141 2698.40283203 2733.78198242 2662.87841797
 2719.06103516 3183.36303711 3158.55615234]

glicko_rd: [62.2126236  63.88693619 62.89942932 88.22782135 61.8838768  96.36142731
 69.92723083 64.38748169 67.01855469 86.38825226 95.05103302 91.4200058
 66.28070831 61.32221985 82.67273712 75.44211578 62.56368637 96.55396271
 64.96870422 81.64781952 78.96452332 65.87309265 59.60514832 81.96681213
 63.06946945 98.95932007 77.1367569  70.93631744 68.83644867 73.08595276
 61.57320404 71.45272064 63.3780632  63.91904831 63.68328094 96.43591309
 65.25708008 63.7203064  64.15467072 88.41366577 64.44595337 62.40243149
 61.61252975 61.70264053 94.65277863 61.79720688 92.8787384  62.73243332
 62.32658005 70.88943481 63.17655563 85.42721558 63.49449539 62.12109375
 62.80210876 63.96965027 63.29454422 69.14508057 64.73596191 63.53691483
 62.85718536 64.35881805 69.69218445 63.88400269 81.44701385 63.83858871
 63.47011948 61.91773987 87.85051727 62.43980026 84.99181366 62.54720306
 71.13111877 66.19393158 63.11523438 62.20595932 61.0750618  62.28667831
 63.32182693 81.85098267 75.89225769 63.14078903 94.84421539 72.39608002
 68.02618408 63.93956375 73.01692963 65.9283371  61.71351242 63.47945786
 84.52325439 64.15975189 98.2502594  62.41737747 63.90584564 62.46834946
 63.92039871 87.67173767 63.21687317 63.80350113 62.91421127 78.35807037
 61.67193222 62.10708618 63.37013245 69.91742706 63.12145615 97.40422058
 65.3931427  77.99343872 65.84127045 79.2244873  62.20954514 76.20652008
 69.47905731 63.55042267 63.55923462 61.24147797 64.2047348  62.50963211
 61.60906601 61.88075638 74.37656403 62.47514725 63.11416626 62.83703232
 63.68675995 63.90636444 65.32378387 62.76159668 72.07436371 62.79454041
 62.70743561 62.80044556 61.68431473 61.85854721 65.19853973 78.40007782
 68.19810486 66.75688171 71.08651733 71.72157288 64.72409821 62.32326508
 65.78112793 84.79548645 61.91302872 62.09346008 64.59590912 77.77586365
 65.19264984 66.40540314 67.74388123 65.87381744 82.10233307 62.7416687
 88.32071686 67.66825867 63.18277359 67.4161911  64.55521393 75.12080383
 77.48336029 99.45391083 64.27410889 92.68630219 64.80610657 64.63291931
 82.68784332 61.89102173 62.39670944 62.72858047 73.22436523 63.8055191
 63.06261444 63.04437637 72.74871063 72.41343689 64.15100098 86.04227448
 69.91700745 62.47516632 71.95135498 61.22727966 66.30027008 63.26490402
 86.33084106 70.10968781 62.73648071 66.06798553 81.83724976 91.20098877
 61.9716568  62.39227676 78.3421936  62.44807816 81.2090683  68.67524719
 66.1461792  62.08693695 67.96865082 61.20103836 66.79121399 91.02068329
 75.03392029 62.40761948 63.65256882 62.63205719 63.52402878 61.70948029
 76.64398956 63.71402359 73.96909332 71.68436432 63.62068939 64.28153992
 72.56520844 65.05850983 66.37217712 90.0329895  71.80524445 63.39701462
 64.15364838 86.36398315 66.70845795 64.95584869 62.2999649  63.76233292
 68.29645538 87.39035797 63.19102478 63.04665756 79.87160492 72.20358276
 63.68702316 69.60442352 61.85775375 67.76546478 62.68707657 64.72398376
 85.78160858 68.38093567 71.45825195 63.09275055 63.36805725 66.74652863
 82.03850555 64.34172821 68.76446533 63.78560638 62.92533493 62.3216362
 66.85299683 63.08346176 61.7645607  67.44289398 61.40673828 67.28181458
 64.91213226 65.80504608 63.62892914 64.77089691 62.79654694 70.97631073
 66.54767609 62.93346405 62.44210815 75.98176575 61.5112114  64.78237152
 75.03977203 62.68473816 93.00205994 68.06945801 66.69165802 92.27671814
 62.65095139 71.68901825 66.45892334 66.41904449 66.51278687 86.28569794
 62.32378769 80.27776337 63.2416687  62.86004639 62.44435883 63.63726807
 69.54990387 88.53588104 77.09086609 61.09288406 71.55458832 70.4056015
 62.92263031 61.28453064 99.6645813  65.44353485 72.16278839 95.38252258
 63.02150726 61.67696762 72.11401367 64.79310608 84.13389587 62.39995575
 98.36660004 61.83556747 65.03295898 63.86365128 68.16591644 63.24372482
 63.25657272 88.54985809 61.7369957  63.00757599 61.49407959 64.49329376
 66.34319305 62.61660004 62.51644516 64.8680954  61.07920456 63.2080574
 62.54406357 72.65429688 62.02750397 63.95231247 62.8646431  62.51575089
 61.77190781 66.42986298 63.85678482 62.87166595 63.8707428  63.79795837
 63.0125351  84.93323517 64.32001495 65.79081726 67.06559753 62.96791077
 65.73708344 61.2557106  62.44504547 82.83514404 68.00076294 63.47782516
 64.06955719 61.60267639 60.74129868 96.59252167 61.11283112 63.20175171
 82.0302887  62.47799301 64.9287262  64.71528625 73.6776886  69.87736511
 61.32943726 70.73223877 65.3425293  67.16410065 64.81806946 62.16591644
 65.53444672 68.91255951 63.0030365  66.26329041 61.5056839  63.82674408
 78.20171356 62.84046173 87.91357422 68.26700592 66.78524017 69.2325592
 63.82945633 63.79198456 79.57936096 62.88488007 66.32125854 65.07359314
 65.85135651 60.96203613 67.69589996 64.84423065 62.64458084 62.63718796

### Checking for Duplicate Data

In [20]:
df.duplicated().any()

np.True_

In [16]:
df = df.drop_duplicates(subset=['game_id', 'subframe'])
# only drop the duplicated where it has the same game_id and subframe
# it is physically and mechanically impossible for a player to place two different pieces at the exact same subframe. A player can only drop one piece at an exact millisecond
df.shape

(7716512, 14)

### Checking for Inconsistent Games

In [ ]:
# Drop games where 'won', 'rating', 'glicko', or 'glicko_rd' are not consistent within a game.
if {"game_id", "won", "rating", "glicko", "glicko_rd"}.issubset(df.columns):
    gchecks = df.groupby("game_id")[
        ["won", "rating", "glicko", "glicko_rd"]].nunique()
    inconsistent_games = gchecks[(gchecks > 1).any(axis=1)].index.tolist()
    print(f"Inconsistent games found: {len(inconsistent_games)}")
    df = df[~df["game_id"].isin(inconsistent_games)]

Inconsistent games found: 0

### Checking for Outliers

In [12]:
# Print min, max, and extreme quantiles for key numeric columns.
num_cols = [
    "cleared",
    "garbage_cleared",
    "attack",
    "btb",
    "combo",
    "immediate_garbage",
    "incoming_garbage",
]
for col in num_cols:
    if col in df.columns:
        high = df[col].quantile(0.999)
        low = df[col].quantile(0.001)
        print(f"{col}: min={df[col].min()}, max={df[col].max()}, 0.1%={
            low}, 99.9%={high}")

cleared: min=0, max=4, 0.1%=0.0, 99.9%=4.0
garbage_cleared: min=0, max=0, 0.1%=0.0, 99.9%=0.0
attack: min=0, max=22, 0.1%=0.0, 99.9%=7.0
btb: min=0, max=54, 0.1%=0.0, 99.9%=19.0
combo: min=0, max=21, 0.1%=0.0, 99.9%=7.0
immediate_garbage: min=0, max=78, 0.1%=0.0, 99.9%=15.0
incoming_garbage: min=0, max=78, 0.1%=0.0, 99.9%=17.0

In [ ]:
num_cols = ["cleared", "garbage_cleared", "attack", "btb", "combo", "immediate_garbage", "incoming_garbage"]

for col in num_cols:
    if col in df.columns:
        top_values = df[col].value_counts().nlargest(5).to_dict()
        
        max_val = df[col].max()
        
        print(f"--- {col} ---")
        print(f"Max Value: {max_val}")
        print(f"Top 5 most common values: {top_values}\n")

--- cleared ---
Max Value: 4
Top 5 most common values: {0: 5587295, 1: 958295, 2: 690330, 4: 381767, 3: 98837}

--- garbage_cleared ---
Max Value: 0
Top 5 most common values: {0: 7716524}

--- attack ---
Max Value: 22
Top 5 most common values: {0: 6033922, 1: 590235, 4: 439143, 2: 207244, 5: 197437}

--- btb ---
Max Value: 54
Top 5 most common values: {0: 3580661, 1: 1467989, 2: 890309, 3: 553606, 4: 388236}

--- combo ---
Max Value: 21
Top 5 most common values: {0: 5596521, 1: 1315814, 2: 445764, 3: 197292, 4: 88032}

--- immediate_garbage ---
Max Value: 78
Top 5 most common values: {0: 6690420, 1: 243668, 5: 150719, 4: 149941, 2: 148039}

--- incoming_garbage ---
Max Value: 78
Top 5 most common values: {0: 5866757, 1: 380037, 5: 290027, 4: 277661, 2: 265844}

### Feature Engineering

In [ ]:
print("CLEANING SUMMARY:")
print(f"Rows after cleaning: {len(df)}")
print(f"Unique games: {df['game_id'].nunique()
      if 'game_id' in df.columns else 'N/A'}")

print("Num placement rows:", len(df))
print("Num unique game_id:", df["game_id"].nunique())
print("game_id dtype:", df["game_id"].dtype)

# Aggregation
# groupby game_id
agg_dict = {
    "subframe": ["max", "count"],
    "cleared": "sum",
    "garbage_cleared": "sum",
    "attack": "sum",
    "t_spin": lambda x: x.isin(["M", "F"]).sum(), 
    "btb": ["mean", "max"],
    "combo": ["mean", "max"],
    "immediate_garbage": ["mean", "max"],
    "incoming_garbage": ["mean", "max"],
    "won": "first",
    "rating": "first",
    "glicko": "first",
    "glicko_rd": "first",
}

game_level = df.groupby("game_id").agg(agg_dict)

game_level.columns = ["_".join([c for c in col if c]) for col in game_level.columns]
game_level = game_level.reset_index()

rename_map = {
    "t_spin_<lambda>": "t_spin_count",
    "won_first": "won",
    "rating_first": "rating",
    "glicko_first": "glicko",
    "glicko_rd_first": "glicko_rd"
}
game_level = game_level.rename(columns=rename_map)

game_level["duration_sec"] = game_level["subframe_max"] / 600
game_level["pps"] = game_level["subframe_count"] / game_level["duration_sec"]
game_level["attack_per_piece"] = game_level["attack_sum"] / game_level["subframe_count"]
game_level["apm"] = (game_level["attack_sum"] / game_level["duration_sec"]) * 60
game_level["tspin_rate"] = game_level["t_spin_count"] / game_level["subframe_count"]

print("Num rows in game_level:", len(game_level))

for col in game_level:
  print(f"{col}: {game_level[col].unique()}")
  print("")

# Export
# game_level.to_csv("./data/game_level.csv", index=False)

CLEANING SUMMARY:
Rows after cleaning: 7716512
Unique games: 76692
Num placement rows: 7716512
Num unique game_id: 76692
game_id dtype: int64
Num rows in game_level: 76692
game_id: [     1      2      3 ... 124030 124031 124032]

subframe_max: [42360 42786 29565 ... 20760 19859 41873]

subframe_count: [196 215 152 136 191 197 123 138  28  33  32  42  40 139 129  56  50  35
  64  34  11  13 333 134 300 119  22  70  31  74  53   5 179 193 374 380
  94  76  68  75 398 410 106 108  63  48  26  15  84 111  39  25  44  52
  47 159 166 103  69  72  30  49  82 248  87  67  61  45  86  73  27 228
 264  77  85  79  92 101 115 107  62  59 145  97  54 171 120  83  80  23
 163 122 279 320 116 102  95 231 223 156  29  99 150 131  17 204 125 105
  93 205 199  38 275  14 209 175 406  43 154 184 172 113  46  65  24 100
  58  60  89  36  91 165 155  20 192  51 135 151 128 190 189  19 140 142
 141 137  21 250  37 176 114  71  81  78 132 130 425 182 164 153 146 149
 104 201 493 162 356 350 238 270  55  57  41  66 282 265 170 143 110 183
  90 124 117 251 235 168 203 212 202 200 133 127 318 286 272 322 331 185
 167 144 216 225 126 334 325 227 388 213 206 109  96 157 210  18 211  10
 262 293  98 255 244 360 396 217 285 161 234 434 395 148 281 147 160  88
 173 226  12 361  16 245 305 112 230 118 301 327 297 600 340 366 169 284
 309 442 207 174 221 240 253 180 187 181 276 303 477 307 274 236 382 188
 186 278 214 195 121 475 415 237 352 246 219 158 269 254 411 252 194 273
 243 222 312 302 424 376 497 257 295 299 256 178 232 277 241 280 224 483
 315 365 364 261 335 294 344 348 317 258 448 417 314 233 319 407 208 529
 450 519 316 218 383 353 347 242 724 310 481 239 249 259 287 306 177 220
 328 247 378 267   7 359 298 304 266 385 339 292 326 367 313 260 569 369
 342 556 346 198 393 370 414 271 391 387 472 229   4 288 468 440 469 289
 324 311 341   6 452 263 428 490 390 283 268 433 392 381 405 462 416 343
 379 337 329 371 404 373 345 372 323 543 494 581 502 463 421 551 458 389
 403 354 394 580 544 330 363 456 408 510 423 384   8 509 338 291 357 505
 591 553 401 431 507 321 336 439 351 386   9 444 377 308 290 461 296 400
 533 429 447 362 499 436 593   3 498 418 399 355 349 332 432 558 613 427
 572 368 486 476 358 443 430 419 420 453 614 480 743 699 422 455 583 567
 717 375 426 402 437 457 413 451 466 485 412 500 579 563 465 459 478 482
 460 491 508 537 409 487 504 570 615 526 627 673 530 446 511 528 449 397
 571 467 473 492 536 520 488 548 644 503 588 454 479 441 521 597 464 489
 586 590 630 445 522 560 518 604 524 534 474   1 484 691 470 517 438 471
 523 501 666 527 674 650 619 549 618 512 559 516 540 554 607 513 609 745
 636 575 599 531 701 589 694 657 629 628 595 547 539]

cleared_sum: [115 133  85  83 107 113  70  73   9  12   7  20  15  81  29  23  17  21
  16   4   2 155  68 137  64  32   8  30  10 117 231 209  54  42  41  38
 240 242  52  58  24  22  26   3  43  45  61  19  13 102  95  60  34  33
   6  44 120  48  37  36  28  27  40  14 147 135  35  25  49  51  62  31
  18  56  84  57  63  74  50  46 166 194 144 156 111  98 114  39 118  71
  47 106  65 157  53   0 132 110  78 230  88 108  76  89  86   5  67 109
 127  91  79  55  59  11  75  90  80 124 100  99  72  87 250 256  97  82
 116 332  94 198 146 160  93  77 151 148 172 142 140 101 126 173 201 175
 197 119 153  66 190 205 123 213 121   1 165 150 145 245 253 164  69 141
 112 258 104 259 247 187 178  96 136 216 195 203 179 143 103 167 171 376
 217 214 229 158 182 273  92 168 169 255 129 280 154 181 125 263 269 128
 130 170 260 186 159 183 191 152 226 307 134 161 162 138 105 176 185 211
 285 252 264 206 122 215 238 275 276 233 249 207 322 313 326 180 139 451
 149 321 131 177 218 221 208 227 228 212 200 210 163 174 335 268 248 196
 299 184 188 241 303 282 266 189 281 235 293 232 224 257 286 236 225 202
 192 199 222 223 239 193 344 315 331 270 237 265 328 336 375 345 318 290
 319 272 234 279 320 377 337 291 219 254 302 348 289 413 301 204 278 267
 380 277 251 274 283 284 338 467 423 310 369 453 246 294 295 261 262 387
 271 220 334 330 354 325 244 312 324 356 243 298 287 350 408 383 292 333
 329 288 306 397 316 374 304 366 386 357 359 314 349 309 341 339 305 353
 385 297 347 367 370 412 429 372 342 308 400 352 362 317 388 434 379 492
 395 460 436 373 437]

garbage_cleared_sum: [0]

attack_sum: [161 126 102  85 128 109  95  84  22  24  14  32  83  73  33  18  39   2
   0 181  76 221   5  43  34  21 125 114 217 227  55  42  57  46 261 237
  71  28  26  38  20   1  62   7  61  81  31  30  11 118  90  64  41  49
  13  53  69 160  67  44  27  10 216 219  74  48  82  58  60  50  79  25
  19  80  29  89  65  70  35  59 192 166  88  56  36   4 153 133 135   9
  17  15  75 154  78  96 111   6 123 116 124  45  37 156 136 240  40 105
  97  23  12   3 130  91 106 137   8 108 162 120 186 167  72 223  51  98
  86 117 107 264 244  52  93  99 151 329 149  94 163 256 236 188 176 104
  54 184 113  16 110  66 145 129 141 140 122 233 119  92 157 144 165 115
 103  47 112  77 169 100  68 182 173 174 307 290  87 185 131 288 250 195
 179 189 164 101 158 225 206 205 159 172 336  63 234 215 214 171 146 142
 134 155 147 148 152 209 333 228 202 200 168 226 212 170 273 222 248 150
 230 262 132 232 346 282 183 399 187 203 197 138 196 257 224 127 175 190
 270 315 274 292 194 180 204 291 199 271 293 360 390 259 139 210 316 352
 303 121 289 201 263 287 178 454 252 220 388 272 177 191 211 143 334 193
 267 241 255 404 235 308 325 322 213 207 198 265 242 310 330 218 208 317
 269 361 283 243 319 278 277 296 311 245 246 231 284 295 281 285 392 389
 427 368 374 254 294 409 357 266 247 306 350 321 441 546 537 251 279 313
 239 327 302 353 337 493 415 309 258 401 298 229 238 260 305 402 299 300
 463 434 276 275 356 280 340 253 453 301 297 324 335 542 539 396 347 568
 268 312 328 314 375 304 249 344 403 363 387 466 426 318 320 359 341 405
 339 331 414 372 430 462 332 411 358 326 437 367 338 345 355 383 514 497
 384 391 492 373 349 422 348 364 342 365 286 528 496 351 370 467 432 369
 371 425 343 447 362 421 428 354 382 456 485 433 509 381 410 393 461 499
 413 442 459 423 323 473 439 445 510 569 536 511 376 486 366]

t_spin_count: [15 12 10  5 11 13  8  4  3  7  1  2  0 16 20 23  6 18 21  9 14 22 26 19
 17 24 25 34 29 27 35 38 33 30 28 31 48 32 39 37 42 36 55 44 41 43 46 56
 60 40 52 50 47 45 51 53 49]

btb_mean: [1.93367347 0.41395349 0.61184211 ... 1.92792793 1.68803419 4.76470588]

btb_max: [ 8  4  3  7  5  2  0  6 13  1 10 12 11 14  9 19 26 15 23 18 25 24 21 20
 16 22 34 17 32 31 37 38 28 27 54 29 30 44 35 47 39 33]

combo_mean: [0.52040816 0.59069767 0.60526316 ... 0.33505155 0.63131313 1.47368421]

combo_max: [ 7  6  8  5  4  3  1  2 12  9 16  0 13 11 10 14 18 17 15 21 19 20]

immediate_garbage_mean: [0.24489796 0.68372093 0.25       ... 1.24719101 1.17171717 1.2195122 ]

immediate_garbage_max: [ 8 13  6  9 11  0  5 15  7 12 10 14  2  4 20  3 16 19 23  1 18 28 17 22
 21 26 31 25 24 27 32 36 40 35 41 34 38 37 30 78 49 42 50 51 29 33 39 59
 77 56 43]

incoming_garbage_mean: [0.57653061 1.43255814 0.60526316 ... 4.21621622 2.31343284 2.24719101]

incoming_garbage_max: [15 13  6 10 11  9  0  5 16 12  8 18  7  2  4 20 14  3 19 29 17  1 28 23
 22 24 21 26 31 25 27 32 34 36 40 35 30 41 38 37 78 49 42 50 51 33 39 66
 77 56 59 44]

won: [1 0]

rating: [24748.52148438 24820.7109375  24788.74414062 24830.14648438
 24859.94726562 24887.21679688 24864.00195312 24961.0234375
 24713.24414062 24827.4140625  24737.203125   24999.52148438
 24991.89257812 24730.4140625  24886.38671875 24929.58984375
 24832.296875   24709.61328125 24917.9140625  24825.25
 24808.39453125 24910.67578125 24713.30664062 24904.13867188
 24964.734375   24952.47265625 24952.4921875  24967.29101562
 24872.34570312 24876.94726562 24857.99023438 24924.22851562
 24834.79101562 24930.44726562 24967.19335938 24974.69140625
 24984.18554688 24767.9375     24914.42578125 24916.20703125
 24886.3359375  24825.11914062 24805.04492188 24750.25
 24755.09960938 24797.26171875 24828.45703125 24894.140625
 24937.1953125  24894.42382812 24917.06445312 24726.19140625
 24766.16210938 24778.4921875  24724.65820312 24867.15234375
 24915.484375   24967.26367188 24987.77734375 24909.37109375
 24933.68359375 24968.21289062 24968.54882812 24882.125
 24847.6328125  24970.16601562 24855.3671875  24820.375
 24704.046875   24936.00390625 24705.21484375 24875.890625
 24995.03515625 24946.27148438 24804.07617188 24763.99804688
 24846.75585938 24777.9609375  24921.703125   24907.27539062
 24906.328125   24829.33984375 24704.90429688 24967.69335938
 24993.1875     24966.7109375  24918.98632812 24984.78125
 24832.32617188 24966.24023438 24952.32421875 24986.44335938
 24774.99414062 24804.71484375 24917.5234375  24903.61523438
 24922.3828125  24850.23242188 24886.25390625 24966.74414062
 24866.59765625 24960.0546875  24722.1796875  24766.71679688
 24902.82226562 24974.93359375 24819.6015625  24941.43359375
 24992.703125   24993.37109375 24963.10546875 24834.36328125
 24741.56835938 24958.17578125 24992.84960938 24948.86132812
 24826.20898438 24798.6953125  24986.93359375 24854.15429688
 24713.00976562 24766.1640625  24978.75976562 24889.35546875
 24933.69335938 24887.78515625 24901.         24892.734375
 24806.29882812 24870.9140625  24984.25       24884.78515625
 24842.48242188 24886.2578125  24739.92578125 24769.52734375
 24998.671875   24997.00195312 24998.93359375 24798.24609375
 24736.40039062 24895.00390625 24954.29296875 24854.8125
 24991.68945312 24958.796875   24900.8828125  24763.46289062
 24973.40820312 24953.33398438 24964.16601562 24987.08984375
 24993.91015625 24989.59375    24705.62109375 24766.66210938
 24767.8671875  24734.80664062 24720.91992188 24908.54882812
 24983.65820312 24730.06054688 24728.65234375 24719.24804688
 24780.74609375 24913.30664062 24910.86132812 24880.11328125
 24963.17382812 24790.30273438 24771.69726562 24699.23242188
 24712.28710938 24939.51367188 24771.61132812 24953.59960938
 24712.21679688 24796.93359375 24967.18554688 24976.8203125
 24801.23632812 24785.734375   24802.02539062 24758.44726562
 24755.80273438 24924.50976562 24753.51367188 24866.14648438
 24898.13085938 24978.76171875 24726.50585938 24705.68359375
 24783.46484375 24736.99023438 24874.74414062 24743.046875
 24908.62304688 24905.26367188 24891.92578125 24708.29296875
 24931.3203125  24715.37890625 24958.45703125 24780.59570312
 24840.68945312 24814.93164062 24964.86132812 24776.51367188
 24936.50585938 24710.98046875 24954.5546875  24885.74804688
 24816.09179688 24953.42578125 24965.05859375 24948.42382812
 24884.2265625  24978.0859375  24724.73828125 24927.80273438
 24965.65039062 24932.29882812 24987.38867188 24982.56640625
 24984.3828125  24798.13085938 24732.0859375  24836.44140625
 24871.70117188 24882.68164062 24873.54882812 24802.390625
 24998.86132812 24998.97265625 24930.5234375  24827.609375
 24786.44335938 24757.734375   24922.74023438 24918.765625
 24913.34765625 24757.06640625 24919.62695312 24923.7734375
 24925.14648438 24711.02539062 24930.203125   24958.91210938
 24728.03515625 24978.92382812 24708.140625   24753.25
 24868.56054688 24951.5859375  24710.39257812 24975.09765625
 24832.38867188 24913.23632812 24915.17773438 24980.4609375
 24995.24414062 24780.73242188 24700.4609375  24930.953125
 24773.16015625 24740.015625   24711.76757812 24802.37890625
 24749.61328125 24948.81835938 24770.15820312 24798.98242188
 24849.01757812 24988.41992188 24764.48242188 24987.23046875
 24858.04101562 24833.46289062 24986.65820312 24941.640625
 24997.12890625 24995.21289062 24767.8203125  24888.34765625
 24890.31445312 24826.51367188 24759.1171875  24904.76367188
 24907.875      24999.2265625  24958.99804688 24801.98632812
 24829.80078125 24971.40429688 24743.98242188 24821.46875
 24845.71289062 24971.57617188 24938.109375   24904.59375
 24974.47070312 24805.10546875 24740.14257812 24981.703125
 24829.84765625 24868.43359375 24714.20898438 24745.89648438
 24979.98632812 24879.50195312 24726.58203125 24854.11132812
 24718.81054688 24950.1328125  24742.10546875 24775.98828125
 24758.03320312 24911.1640625  24736.77929688 24846.92382812
 24927.6796875  24940.97070312 24817.90429688 24914.20703125
 24860.79296875 24996.79882812 24881.52148438 24848.15820312
 24925.10546875 24750.02539062 24941.3203125  24892.97070312
 24714.67578125 24711.70703125 24855.11132812 24855.29492188
 24754.22265625 24980.10742188 24908.78125    24854.3828125
 24839.40234375 24910.90625    24774.08789062 24707.42578125
 24739.2890625  24703.3671875  24844.0859375  24893.0546875
 24899.9609375  24702.86328125 24744.36914062 24904.50390625
 24849.51367188 24940.67578125 24861.546875   24790.9453125
 24951.27539062 24980.47070312 24864.13085938 24954.94921875
 24716.33789062 24718.02539062 24834.28125    24985.39257812
 24950.38867188 24805.1796875  24854.05859375 24833.52148438
 24792.19726562 24875.2265625  24698.32421875 24984.56054688
 24777.52539062 24880.12890625 24964.18359375 24988.359375
 24989.22460938 24777.22265625 24732.35742188 24859.4375
 24705.18554688 24724.53320312 24983.17773438 24930.8671875
 24927.77539062 24705.67382812 24945.84570312 24979.5546875
 24875.46289062 24818.54882812 24986.8671875  24746.52148438
 24957.203125   24925.12304688 24972.20703125 24874.13085938
 24989.39648438 24945.80273438 24832.98046875 24843.67382812
 24982.59375    24964.94335938 24854.55273438 24905.8671875
 24967.43554688 24863.0546875  24949.1640625  24910.97265625
 24708.03710938 24747.53710938 24993.93554688 24942.76171875
 24701.66210938 24857.76953125 24719.10351562 24974.3046875
 24734.41796875 24954.66601562 24768.375      24995.00976562
 24794.84960938 24717.0859375  24844.48632812 24983.48242188
 24901.81640625 24870.39648438 24939.99414062 24729.76757812
 24712.546875   24755.90039062 24863.47070312 24743.76367188
 24707.27929688 24808.79492188 24958.87109375 24996.57617188
 24736.48242188 24740.04101562 24748.25390625 24859.75195312
 24978.44140625 24708.35351562 24724.66992188 24781.5625
 24959.70898438 24916.77148438 24765.00390625 24772.58203125
 24738.13085938 24734.87304688 24798.4765625  24742.29296875
 24742.71679688 24982.875      24921.29492188 24907.65234375
 24991.51757812 24990.72070312 24704.42382812 24775.7109375
 24806.0546875  24771.93554688 24704.58007812 24699.66015625
 24729.9921875  24813.96679688 24700.94335938 24716.84179688
 24826.921875   24781.72460938 24866.28125    24699.09375
 24792.16992188 24725.73828125 24760.60546875 24841.3671875
 24923.4140625  24971.82617188 24707.05078125 24698.078125
 24872.7421875  24738.56445312 24777.04296875 24707.30859375
 24762.96679688 24956.55859375 24953.96875   ]

glicko: [2701.88769531 2791.86694336 2748.19384766 2810.68676758 2856.23876953
 2921.94799805 2867.17602539 3193.43676758 2668.73828125 2811.63354492
 2694.09741211 4373.41992188 3606.390625   2683.19628906 2917.22607422
 3043.38476562 2809.01074219 2677.77612305 2998.0534668  2806.0456543
 2780.39038086 2976.21459961 2666.36816406 2965.27880859 3219.05810547
 3161.76049805 3148.01806641 3241.78442383 2883.42236328 2894.95654297
 2852.46777344 3018.0234375  2813.2590332  3041.14868164 3238.32104492
 3327.24121094 3430.53808594 2723.65039062 2986.76074219 2998.9921875
 2912.19921875 2797.8996582  2768.95214844 2703.54345703 2710.07519531
 2758.68212891 2808.7890625  2930.23535156 3067.26147461 2934.39111328
 2994.5859375  2688.29321289 2721.55786133 2735.40722656 2678.08398438
 2870.94189453 2989.67138672 3241.66333008 3497.8293457  2971.41552734
 3053.20141602 3246.93554688 3251.95581055 2902.40063477 2842.30395508
 3263.3137207  2848.35644531 2790.6652832  2662.07958984 3062.37573242
 2665.88891602 2888.30761719 3738.3203125  3110.00268555 2768.16992188
 2718.68383789 2832.23388672 2734.83154297 3009.77294922 2974.01782227
 2968.29614258 2804.609375   2663.22045898 3246.90600586 3653.15917969
 3234.61132812 3005.19189453 3440.99487305 2808.75       3230.70361328
 3143.55224609 3470.34326172 2732.71118164 2768.78588867 2996.35327148
 2954.78857422 3012.32006836 2843.30688477 2911.52124023 3234.81176758
 2869.4387207  3194.42358398 2675.34472656 2721.71313477 2952.99633789
 3310.58935547 2789.96337891 3103.16601562 3633.47241211 3665.80639648
 3208.55981445 2818.6730957  2694.66918945 3181.07470703 3641.37182617
 3121.75805664 2799.96826172 2760.36303711 3479.99365234 2845.79711914
 2666.72338867 2721.01245117 3358.37133789 2918.50219727 3053.3527832
 2914.9387207  2948.24047852 2927.23120117 2771.97973633 2878.04003906
 3435.59936523 2907.97802734 2825.58203125 2911.36303711 2692.81958008
 2724.83447266 4080.13330078 3866.01464844 4139.84667969 2761.74609375
 2692.54248047 2932.78442383 3151.78369141 2846.91772461 3599.60424805
 3190.13623047 2947.21704102 2718.04711914 3293.86987305 3152.53076172
 3215.89453125 3484.44604492 3682.38134766 3540.67749023 2660.79345703
 2721.86572266 2733.66040039 2689.69726562 2674.63598633 2970.68823242
 3421.56518555 2687.77587891 2682.5144043  2688.27978516 2738.50634766
 2988.13696289 2976.30273438 2898.24072266 3218.47607422 2749.80249023
 2727.51464844 2654.65527344 2670.09716797 3077.78588867 2727.64404297
 3147.04638672 2667.01708984 2762.22216797 3238.48291016 3336.4050293
 2764.29833984 2744.30957031 2768.76025391 2712.2109375  2711.06542969
 3019.34130859 2707.90722656 2871.44921875 2940.3425293  3353.62451172
 2679.87963867 2659.91699219 2741.35424805 2690.08129883 2886.98510742
 2696.265625   2974.02685547 2961.95361328 2926.17626953 2662.55639648
 3045.83422852 2668.79003906 3177.8659668  2750.00878906 2825.03686523
 2782.96313477 3220.2800293  2733.23046875 3064.91430664 2664.8894043
 3159.43774414 2910.54833984 2789.10375977 3150.30419922 3221.75146484
 3119.85375977 2910.82055664 3344.87036133 2679.36401367 3044.91064453
 3226.8034668  3048.01025391 3489.27441406 3418.41235352 3434.65063477
 2760.93237305 2685.16064453 2816.04931641 2881.8684082  2914.11645508
 2883.63867188 2765.8840332  4127.34423828 4153.10693359 3041.33447266
 2804.42138672 2744.9753418  2713.69580078 3013.00805664 3000.68969727
 2983.31298828 2713.18969727 3004.25048828 3016.71557617 3021.61010742
 2666.59887695 3049.21826172 3179.57421875 2683.40332031 3354.43530273
 2662.68798828 2706.94506836 2874.89453125 3135.90991211 2664.36743164
 3312.60913086 2808.73925781 2982.76708984 2989.40454102 3375.35961914
 3744.54174805 2739.01538086 2655.12939453 3042.65844727 2730.67163086
 2693.32275391 2665.84570312 2766.92895508 2702.80664062 3122.10058594
 2727.37011719 2761.24023438 2847.98950195 3513.93994141 2720.78833008
 3487.24121094 2852.96630859 2814.40185547 3475.82641602 3087.01855469
 3878.85327148 3759.64501953 2723.03930664 2918.92602539 2921.09350586
 2800.17675781 2713.35131836 2958.41455078 2969.70361328 4221.25341797
 3180.48144531 2764.66357422 2808.59545898 3274.71289062 2697.38989258
 2792.05224609 2838.61401367 3276.82543945 3075.71069336 2961.78100586
 3303.7746582  2769.05566406 2695.6081543  3392.04443359 2807.28881836
 2872.890625   2673.09082031 2699.015625   3368.64257812 2896.59594727
 2681.77490234 2845.99414062 2672.66674805 3130.74584961 2695.06396484
 2732.73999023 2711.84643555 2977.07055664 2691.20898438 2833.0847168
 3030.29492188 3084.67407227 2786.76928711 2985.69335938 2858.08251953
 3854.64160156 2900.3293457  2835.72119141 3021.25610352 2703.57519531
 3084.85986328 2928.85302734 2668.99633789 2665.92993164 2848.04467773
 2848.34912109 2708.22070312 3370.19970703 2970.03491211 2847.46435547
 2822.12915039 2975.66943359 2731.46411133 2661.50708008 2692.4230957
 2660.03417969 2830.3112793  2927.84472656 2945.64990234 2657.51660156
 2697.07250977 2964.04638672 2837.03076172 3082.61206055 2860.46435547
 2750.81469727 3135.08862305 3374.90185547 2867.32080078 3158.11669922
 2669.72314453 2674.52368164 2813.18212891 3452.45019531 3130.3046875
 2769.32714844 2846.77856445 2811.07006836 2752.58349609 2888.3737793
 2653.46704102 3436.04541016 2735.32763672 2897.5690918  3219.52319336

### Further Preprocessing

In [37]:
# drop games that lasted for 10 seconds or less to rule out instant disconnects/forfeits
game_level2 = game_level[game_level["duration_sec"] >= 10.0].copy()
game_level2.shape

(70246, 24)

In [39]:
# drop intermediate columns and identifier
cols_to_drop = [
    "game_id",
    "subframe_max",
    "subframe_count",
    "cleared_sum",
    "garbage_cleared_sum",   
    "attack_sum",
    "t_spin_count"
]

final_df = game_level.drop(columns=cols_to_drop)
final_df.head()

,btb_mean,btb_max,combo_mean,combo_max,immediate_garbage_mean,immediate_garbage_max,incoming_garbage_mean,incoming_garbage_max,won,rating,glicko,glicko_rd,duration_sec,pps,attack_per_piece,apm,tspin_rate
0,1.933673,8,0.520408,7,0.244898,8,0.576531,15,1,24748.521484,2701.887695,62.212624,70.600000,2.776204,0.821429,136.827195,0.076531
1,0.413953,4,0.590698,6,0.683721,13,1.432558,13,0,24820.710938,2791.866943,63.886936,71.310000,3.015005,0.586047,106.015987,0.055814
2,0.611842,3,0.605263,8,0.250000,6,0.605263,6,1,24820.710938,2791.866943,63.886936,49.275000,3.084729,0.671053,124.200913,0.065789
3,0.786765,4,0.588235,6,0.551471,9,1.227941,10,0,24748.521484,2701.887695,62.212624,49.283333,2.759554,0.625000,103.483260,0.036765
4,1.277487,7,0.539267,5,0.366492,11,0.691099,11,1,24748.521484,2701.887695,62.212624,69.525000,2.747213,0.670157,110.463862,0.057592